# Generated by Django 3.2.9 on 2021-11-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_forget_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=254768651609),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wish_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
