# Generated by Django 3.2.9 on 2021-11-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_contact_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wish_prod',
            field=models.CharField(default='ads123', max_length=50, unique=True),
        ),
    ]
