# Generated by Django 3.2.9 on 2021-11-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cut_through_price',
        ),
        migrations.AddField(
            model_name='product',
            name='pair_with',
            field=models.ManyToManyField(blank=True, related_name='_shop_product_pair_with_+', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
