# Generated by Django 3.2.9 on 2021-11-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211112_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.BigIntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.BigIntegerField(null=True),
        ),
    ]
